### ISSUE TITLE
Create parts list for Trailcam unit

### ISSUE THREAD

**Issue by nicolasbock** [nicolasbock/extreme-lion-challenge#29]
The trailcam unit consists of

1. Trailcam
   The trailcam needs to be connected to the Pi Zero. This could be done via USB cable to read out the trailcam's SD card. Wireless is another option.
3. Raspberry [Pi Zero W](https://www.raspberrypi.com/products/raspberry-pi-zero-w/)
4. Enclosure
   The unit needs to be weather proofed.
6. Power supply
   We need to spec the power requirements of the unit (see #27 and #30)
8. Solar panels or battery pack

**Comment by viswana71** [comment]
I need to check if the current trailcam works with wifi. I think it does. Right now we are using the cellular option but I think we want to switch to a local wifi network at the stables.

**Comment by viswana71** [comment]
We should also figure out the cost of the different items and how to connect these together.
